- name: Check if systemd.unified_cgroup_hierarchy=0 is in /proc/cmdline
  shell: "grep 'systemd.unified_cgroup_hierarchy=0' /proc/cmdline"
  register: unified_cgroup_hierarchy
  ignore_errors: true
  failed_when: false

- block:
  - name: Append systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX
    shell: |
      GRUB_FILE="/etc/default/grub"
      SEARCH_PATTERN="^GRUB_CMDLINE_LINUX="
      APPEND_TEXT="systemd.unified_cgroup_hierarchy=0 "

      if ! grep -q "systemd.unified_cgroup_hierarchy=0" "$GRUB_FILE"; then
          sed -i.bak.$(date +%Y%m%d-%H%M%S) "/$SEARCH_PATTERN/s/\"/& $APPEND_TEXT/" "$GRUB_FILE"
      fi
    args:
      executable: /bin/bash
    register: grub_update

  - name: Update GRUB
    command: update-grub

  - name: "Reboot the system because GRUB updated. You can rerun this script when system running"
    shell: reboot
    args:
      executable: /bin/bash
    become: yes
    ignore_errors: yes

  - name: Wait for the system to reboot
    wait_for:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port | default(22) }}"
      state: started
      delay: 15
      timeout: 300
    delegate_to: localhost
    become: false

  when:
  - unified_cgroup_hierarchy.rc != 0
