- name: Set node_interface_name
  include_role:
    name: utils/set-hostnetworks

- name: Is Support 1G hugepage
  shell: |
    cat /proc/cpuinfo | grep pdpe1gb > /dev/null
  register: is_support_1g_hugepage
  changed_when: false
  failed_when: false

- name: Set host_enable_hugepage to true
  set_fact:
    host_enable_hugepage: true
  when:
  - enable_hugepage is defined
  - is_controller_node|default(false)|bool == false
  - is_support_1g_hugepage.rc == 0
  - (is_centos_x86 is defined and is_centos_x86 | default(false) | bool) == true
    or (is_openeuler_x86 is defined and is_openeuler_x86 | default(false) | bool) == true
    or (is_ubuntu_based_x86 is defined and is_ubuntu_based_x86 | default(false) | bool) == true
    or (is_debian_based_x86 is defined and is_debian_based_x86 | default(false) | bool) == true
  - onecloud_version is defined
  - onecloud_version is version('v3.10', '>=')
  - ansible_architecture == 'x86_64'
  - ansible_memtotal_mb >= 30*1024 # if total memory size greater then 30g

- name: Make /etc/yunion directory
  ansible.builtin.file:
    path: "/etc/yunion"
    mode: 0755
    state: directory

- name: Copy host.conf to /etc/yunion/host.conf with hugepage option {{ host_enable_hugepage }}
  template:
    src: "host.conf.j2"
    dest: "/etc/yunion/host.conf"
    owner: root
    group: root
    mode: 0644
    force: false
